language: python
before_install:
  - pip install codecov
after_success:
  - codecov
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           
      dist: xenial
script: py.test
